<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-9BI5PNMM" failures="1" tests="2" name="Test" time="0.121" errors="0" timestamp="2021-07-04T22:38:00 EDT">
  <testcase classname="tc.suitea.Login" name="login" time="0.016">
    <failure type="java.lang.AssertionError" message="Failed Because of 404 error">
      <![CDATA[java.lang.AssertionError: Failed Because of 404 error
at tc.suitea.Login.login(Login.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="tc.suitea.LoginTest" name="login" time="0.003"/>
</testsuite> <!-- Test -->
